### ISSUE TITLE
upgrade to assistants API v2

### ISSUE THREAD

**Issue by zarifaziz** [RaheesAhmed/Assistant-Api#1]
This sample repo is great, but my use case requires the latest `gpt-4o` model and file-search tool which only works in the latest v2 version. Could you please upgrade the code to v2? :)

**Comment by RaheesAhmed** [comment]
The new Version is updated with all Features provided from openai assistant api kindly check it here https://github.com/RaheesAhmed/openai-assistants-api-v2
